// import '../libs_drpy/jsonpathplus.min.js'; //htmlParser里引入过了
// globalThis.JSONbig = JSONbig; // 必须在drpyS.js里引入
globalThis.reqs = reqs;
globalThis.forge = forge
globalThis.misc = misc;
globalThis.utils = utils;
globalThis.COOKIE = COOKIE;
globalThis.ENV = ENV;
globalThis.Quark = Quark;
globalThis.UC = UC;
globalThis.Ali = Ali;
globalThis.Cloud = Cloud;
globalThis.Yun = Yun;
globalThis.Pan = Pan;
globalThis.Baidu = Baidu;
globalThis.AIS = AIS;
globalThis.zlib = zlib;
globalThis.minizlib = minizlib
globalThis.XMLHttpRequest = XMLHttpRequest;
globalThis.WebSocket = WebSocket;
globalThis.WebSocketServer = WebSocketServer;